import { error } from '@sveltejs/kit';
import { marked } from 'marked';
import { dev } from '$app/environment';
import { weeks, introductoryReadings, type Reading } from '$lib/data/syllabus';
import { slugify } from '$lib/utils/slug';
import type { PageServerLoad } from './$types';

interface ReadingMeta {
	reading: Reading;
	weekNumber?: number;
	weekTitle?: string;
	isAdditional: boolean;
	isIntroductory: boolean;
}

// Built once per Worker isolate, not per request.
function buildMetaMap(): Map<string, ReadingMeta> {
	const map = new Map<string, ReadingMeta>();
	for (const reading of introductoryReadings) {
		map.set(slugify(reading.pdf), { reading, isAdditional: false, isIntroductory: true });
	}
	for (const week of weeks) {
		for (const reading of week.readings) {
			map.set(slugify(reading.pdf), {
				reading,
				weekNumber: week.number,
				weekTitle: week.title,
				isAdditional: false,
				isIntroductory: false
			});
		}
		for (const reading of week.additionalReadings) {
			map.set(slugify(reading.pdf), {
				reading,
				weekNumber: week.number,
				weekTitle: week.title,
				isAdditional: true,
				isIntroductory: false
			});
		}
	}
	return map;
}

const metaMap = buildMetaMap();

export const prerender = false;

export const load: PageServerLoad = async ({ params, fetch, platform, url }) => {
	const meta = metaMap.get(params.slug);
	if (!meta) error(404, 'Reading not found');

	// Reading content lives at static/reading-content/<slug>.md (generated by
	// scripts/generate-readings.js). Fetched per-request so the 5+ MB of
	// markdown never enters the Worker bundle.
	//
	// In production on Cloudflare, fetch on a relative URL doesn't route to
	// static assets — it makes an outbound request to the custom domain
	// which loops and 522s. Use the ASSETS binding when available (prod);
	// fall back to event.fetch in dev where Vite serves the static dir.
	const path = `/reading-content/${params.slug}.md`;
	// In dev: Vite serves static/ at the same URL, and event.fetch routes
	// through Vite. In prod: the ASSETS binding is the only way that doesn't
	// loop through the custom domain.
	const res =
		!dev && platform?.env?.ASSETS
			? await platform.env.ASSETS.fetch(new URL(path, url.origin).toString())
			: await fetch(path);
	if (!res.ok) error(404, 'Reading content not found');
	const raw = await res.text();
	const content = await marked(raw);

	return {
		content,
		slug: params.slug,
		title: meta.reading.title,
		author: meta.reading.author,
		pdf: meta.reading.pdf,
		weekNumber: meta.weekNumber,
		weekTitle: meta.weekTitle,
		isAdditional: meta.isAdditional,
		isIntroductory: meta.isIntroductory
	};
};
